---
# Don't specify IPv6 ranges. Checking every IPv6 address in a given range is
# inefficient, resource-heavy and slow.

ip_networks:
  - 2001:0db8::/128
  - 198.51.100.0/24

checkers:
  snds:
    key: '4efe7ddc-64df-46da-ad9e-dd5212c2e6c0'
  dns:
    hosts:
      - b.barracudacentral.org
      - bl.spamcop.net
      - cbl.abuseat.org
      - combined.rbl.msrbl.net
      - dnsbl.antispam.or.id
      - dnsbl.sorbs.net
      - drone.abuse.ch
      - dsn.rfc-ignorant.org
      - dul.dnsbl.sorbs.net
      - dyna.spamrats.com
      - http.dnsbl.sorbs.net
      - images.rbl.msrbl.net
      - korea.services.net
      - l1.spews.dnsbl.sorbs.net
      - l2.spews.dnsbl.sorbs.net
      - misc.dnsbl.sorbs.net
      - noptr.spamrats.com
      - pbl.spamhaus.org
      - phishing.rbl.msrbl.net
      - postmaster.rfc-ignorant.org
      - psbl.surriel.com
      - rbl.spamlab.com
      - rbl.suresupport.com
      - relays.bl.kundenserver.de
      - relays.nether.net
      - sbl.spamhaus.org
      - smtp.dnsbl.sorbs.net
      - socks.dnsbl.sorbs.net
      - spam.dnsbl.sorbs.net
      - spam.rbl.msrbl.net
      - spam.spamrats.com
      - spamguard.leadmon.net
      - spamrbl.imp.ch
      - tr.countries.nerd.dk
      - truncate.gbudb.net
      - unsure.nether.net
      - virus.rbl.msrbl.net
      - web.dnsbl.sorbs.net
      - whois.rfc-ignorant.org
      - wormrbl.imp.ch
      - xbl.spamhaus.org
      - zen.spamhaus.org
      - zombie.dnsbl.sorbs.net
